new_words = {
    'citron': -3.0,  
    'hidenburg': -3.0,        
    'moon': 4.0,
    'highs': 2.0,
    'mooning': 4.0,
    'long': 2.0,
    'short': -2.0,
    'call': 4.0,
    'calls': 4.0,    
    'put': -4.0,
    'puts': -4.0,    
    'break': 0.5,
    'tendie': 2.5,
    'tendies': 2.7,
    'town': 0.5,     
    'overvalued': -3.0,
    'undervalued': 3.0,
    'buy': 4.0,
    'sell': -4.0,
    'gone': -1.0,
    'gtfo': -1.0,
    'paper': -1.9,
    'bullish': 3.7,
    'bearish': -3.7,
    'bagholder': -2.1,
    'stonk': 1.0,
    'green': 2.7,
    'money': 1.3,
    'print': 2.8,
    'rocket': 2.2,
    'bull': 4.0,
    'bear': -4.0,
    'pumping': 1.5,
    'sus': -2.0,
    'offering': -2.3,
    'rip': -4.0,
    'downgrade': -3.0,
    'upgrade': 3.0,     
    'maintain': 1.0,          
    'pump': 1.9,
    'hot': 1.5,
    'drop': -2.5,
    'rebound': 1.5,  
    'crack': -2.5,
    'cracks': -3.2,
    'gang': 2.0,
    'scam': -2.0,
    'chamath': -2.0,
    'snake': -1.0,
    'squezze': 3.0,
    'bag': -4.0,
    'fly': 2.0,     
    'way': 2.0,     
    'high': 2.0,
    'volume': 2.5,
    'low': -2.0,
    'trending': 0.0,
    'upwards': 3.0,
    'prediction': 1.0,     
    'cult': -1.0,     
    'big': 2.0,
    'margin': -1.0,
    'support': 3.5,
    'resistance': -3.5,
    'gap': 0.0,
    'gap up': 3.0,
    'gap-up': 3.0,
    'gap down': -3.0,
    'gap-down': -3.0,
    'elon': 1.0,
    'down': -3.0,
    'downwards': -3.0}

FULL_TICKERS = [
    'AA','AAPL','ABC','ABNB','ADM','ADMA','ALB','AMZN','APO','ARKK',
    'B','BA','BABA','BAC','BAH','BE','BITO','BUD','BYND',
    'C','CBOE','CBT','CCJ','CLX','CMP','COIN','COST','CPNG','CRSP','CTVA','CVS',
    'D','DAL','DB','DELL','DIA','DKNG','DLTR','DPZ',
    'EBAY','ECL','EEM','ELF','ENPH','ETN',
    'F','FAZE','FDX','FEZ','FOX','FSS',
    'GD','GLD','GOOGL','GS',
    'H','HD','HPQ','HRL','HOOD','HSBC','HSY',
    'ICE','ICLN','ICLR','INTC','INTU','IR','IRM','IWM','IYT',
    'JPM','JEF','JETS','JJSF',
    'K','KALU','KIE','KMB','KO','KR','KRON',
    'L','LAND','LIN','LQDA','LULU','LVS','LYB','LYV',
    'M','MA','MCD','MDB','META','MJ','MMM','MO','MOS','MPW','MRK','MS','MSCI','MSFT','MSFT','MSTR',
    'NDAQ','NFLX','NIO','NKE','NOC','NVDA','NVO',
    'O','OC','ODP','OKTA','OTIS',
    'PBR','PFE','PG','PH','PLNT','PM','PNC','PRU','PYPL',
    'QCOM','QQQ','QSR','QYLD',
    'RACE','RBLX','RDFN','RICK','RIOT','RKT','RMAX','ROKU','RSG','RTX',
    'SAM','SBUX','SCL','SCHW','SHOP','SIMO','SLM','SLV','SNAP','SOCL','SOFI','SPG','SPOT','SPY','SQ','SQM','SQSP','STT','SWBI','SYK',
    'T','TAN','TD','TECK','TGT','TLT','TM','TMUS','TOL','TROW','TSLA','TSM','TTD','TXN',
    'U','UAL','UBER','UBS','ULTA','UNH','UNP','UPST','USB','USFD','UUP','UVV','UWMC',
    'V','VALE','VIRT','VRTX','VZ',
    'W','WBA','WCN','WFC','WM','WMT','WTFC','WTI','WTW','WMG','WU',
    'X','XHB','XLF','XLI','XLK','XLP','XLRE','XLU','XLV','XOM','XPH','XRT',
    'YETI','YUM',
    'Z','ZM','ZTS']